### ISSUE TITLE
Tooltip remains visible after clicking a button

### ISSUE THREAD

**Issue by p8952** [CreativeBulma/bulma-tooltip#1]
When I add a tooltip to a button, the tooltip remains shown after the button is clicked, even when the mouse is moved off the button.

It remains visible until you click somewhere else and the button becomes unfocused.

You can see this happening on the demo page: https://demo.creativebulma.net/components/tooltip/1.0/get-started/

![screenshot-demo creativebulma net-2020 03 28-13_45_52](https://user-images.githubusercontent.com/2962587/77824440-8e508d00-70fa-11ea-9b18-6966ffc01d0c.gif)

**Comment by CreativeBulma** [comment]
Hi @p8952,

thanks for reporting this.
This behavior is due to the fact we are using `focus` pseudo class to display the tooltip for accessibility reason.

I'm wondering if it's a good idea to display tooltip on focus.
I'll have to run some test to see if removing display on focus does not break the system on mobile.
